### ISSUE TITLE
ordered-set doesn't implement Sequential interface

### ISSUE THREAD

**Issue by luminusian** [clj-commons/ordered#29]

**Comment by lsh-0** [comment]
+1 - just encountered this attempting to access first item in ordered map.

**Comment by jafingerhut** [comment]
@lsh-0 What operation were you trying to do on an ordered map that failed?  The function clojure.core/first works fine for me, as well as clojure.core/seq, but perhaps you were trying something else?

```clojure
user=> (require '[flatland.ordered.set :as os])
nil
user=> (def s1 (os/ordered-set 4 3 1 8 2))
#'user/s1
user=> (first s1)
4
user=> (seq s1)
(4 3 1 8 2)
```

**Comment by lsh-0** [comment]
I do believe I was trying to get the value at a specific index:

https://bitbucket.org/lskibinski/bw2-swing-client/src/6df4d8144d58ac6398adc2ec65697d50d5a7fbf8/src/bw2_swing_client/ui.clj?at=default&fileviewer=file-view-default#ui.clj-295:299

I was expecting something like this to work:
```clojure
user=> (def m1 (om/ordered-map 5 6 3 4 1 2))
user=> (nth m1 2)
3
```

**Comment by jafingerhut** [comment]
It is easy to make a sorted set or map implement the Sequential interface, and this does allow clojure.core/nth to work on it, but it also causes this behavior, which seems undesirable:

```clojure
user=> (require '[flatland.ordered.set :as os])
nil
user=> (def s1 (os/ordered-set 5 10 7))
#'user/s1
user=> s1
#ordered/set (5 10 7)

;; this looks expected
user=> (= s1 [5 10 7])
false

;; this looks wrong.
user=> (= [5 10 7] s1)
true
```
The built-in Clojure sorted-set and sorted-map also do not implement the Sequential interface.  It seems to me it is better if ordered-map and ordered-set also do not, for the strange equality behavior that would result as shown above.

**Comment by jafingerhut** [comment]
On any of ordered-set, ordered-map, or Clojure's built-in sorted-set and sorted-map, you can call nth on the result of (seq m), rather than directly on m (results shown below are with the latest checked-in version of this library, unmodified, not my locally modified one mentioned above):
```clojure
user=> (require '[flatland.ordered.set :as os])
nil
user=> (def s1 (os/ordered-set 5 10 7))
#'user/s1
user=> s1
#ordered/set (5 10 7)
user=> (nth s1 1)

UnsupportedOperationException nth not supported on this type: OrderedSet  clojure.lang.RT.nthFrom (RT.java:798)
user=> (nth (seq s1) 1)
10
user=> (def s2 (sorted-set 5 10 7))
#'user/s2
user=> s2
#{5 7 10}
user=> (nth s2 1)

UnsupportedOperationException nth not supported on this type: PersistentTreeSet  clojure.lang.RT.nthFrom (RT.java:798)
user=> (nth (seq s2) 1)
7
```

**Comment by lsh-0** [comment]
very strange comparison behaviour! 

> you can call nth on the result of (seq m), rather than directly on m

yes, this is essentially what I ended up doing. 

Thank you for the elaboration, it's appreciated.

**Comment by danielcompton** [comment]
I think @jafingerhut has covered this pretty well (thanks!), will close for now. The strange equality semantics seem pretty undesirable, especially when this would have different behaviour from the sorted-sets and maps.
