### ISSUE TITLE
[1.5.6] Must hint overloaded method: toArray

### ISSUE THREAD

**Issue by oVerde** [clj-commons/ordered#40]
Happening in Version 1.5.6
Exception in thread "main" Syntax error compiling deftype* at (flatland/ordered/set.clj:19:1). 
Must hint overloaded method: toArray

**Comment by jafingerhut** [comment]
There is a PR for this: https://github.com/amalloy/ordered/pull/37/files

**Comment by slipset** [comment]
Should be fixed now.

**Comment by slipset** [comment]
Should be fixed now.

**Comment by metasoarous** [comment]
Is this fix reflected in the latest release (1.5.7 as of this writing)?

**Comment by metasoarous** [comment]
I confirmed that 1.5.7 does resolve this issue. Thanks!
