### ISSUE TITLE
Is it possible to get the min/max element?

### ISSUE THREAD

**Issue by hinamizawa** [clj-commons/ordered#49]
As the title says, is it possible to add that feature?

**Comment by danielcompton** [comment]
You can call `first` or `(first (rseq` to get the min and max elements. Does that work?

**Comment by hinamizawa** [comment]
> You can call `first` or `(first (rseq` to get the min and max elements. Does that work?

Thanks. How about the support of comparator?

**Comment by jafingerhut** [comment]
The entire purpose of this library is to create data structures where the order of the elements is the order that they were inserted, not based upon any comparator.  If you want sort sets or maps sorted using a comparator, Clojure has built in sorted-set and sorted-map data structures for this purpose.

**Comment by hinamizawa** [comment]
> The entire purpose of this library is to create data structures where the order of the elements is the order that they were inserted, not based upon any comparator. If you want sort sets or maps sorted using a comparator, Clojure has built in sorted-set and sorted-map data structures for this purpose.

Thank you for your clarification.
