### ISSUE TITLE
Strange rendering at the repl

### ISSUE THREAD

**Issue by crinklywrappr** [clj-commons/ordered#57]
I'm seeing this at a fresh repl, using clojure 1.10.0 and ordered 1.5.9.  Any idea what's causing it?

>(ordered-map :a 1 :b 2)
```clojure
#ordered/map ([:a 1] [:b 2])
```
>(.toString (ordered-map :a 1 :b 2))
```clojure
"{:a 1, :b 2}"
```

**Comment by jafingerhut** [comment]
Which of those do you consider unexpected?

The `#ordered/map ([:a 1] [:b 2])` is a tagged literal representation of the ordered map that, if printed and read back in, will preserve the insertion order.  See more about tagged literals here in the Clojure documentation: https://clojure.org/reference/reader#tagged_literals

The map representation `{:a 1, :b 2}`, if printed and read back in, will almost never preserve the insertion order.

**Comment by crinklywrappr** [comment]
I expected the tagged literal to have the same representation as a normal map eg

```clojure
#ordered/map ([:a 1] [:b 2])

**Comment by crinklywrappr** [comment]
Whoops. I pressed the wrong button on my phone.

**Comment by danielcompton** [comment]
I think this is expected behaviour, as @jafingerhut said, reading this back in for larger maps would return an undefined order. Some tests for this could be a good idea if they don't already exist.
