### ISSUE TITLE
Runtime resolve bloats native image size

### ISSUE THREAD

**Issue by borkdude** [clj-commons/ordered#71]
It's a known problem that runtime resolve isn't good for native image size. When upgrading from 1.5.9 to 1.15(!).10 I noticed that babashka's image size grew from 75mb to 120mb. This is due to a `resolve` call in a reader function. I will follow up with a PR.

**Comment by marksto** [comment]
This change causes Martian's CLJS build test to fail:
https://app.circleci.com/pipelines/github/oliyh/martian/321/workflows/124cd92b-ee0d-4c83-8e4c-1b54f87dd2a7/jobs/619

<img width="1354" alt="Image" src="https://github.com/user-attachments/assets/08e484d3-3374-4f8d-be6b-c47a27eb27a7" />

Wonder why. @borkdude, any thoughts?
