### ISSUE TITLE
OrderedSet/hashCode throws an NPE if it contains nil

### ISSUE THREAD

**Issue by NoahTheDuke** [clj-commons/ordered#73]
Repo:

```clojure
(.hashCode (os/ordered-set nil :a :b :c))
```

Stack trace:

```clojure
#error {
 :cause nil
 :via
 [{:type java.lang.NullPointerException
   :message nil
   :at [flatland.ordered.set.OrderedSet$fn__4371 invoke "set.clj" 59]}]
 :trace
 [[flatland.ordered.set.OrderedSet$fn__4371 invoke "set.clj" 59]
  [clojure.core$map$fn__5935 invoke "core.clj" 2770]
  [clojure.lang.LazySeq sval "LazySeq.java" 42]
  [clojure.lang.LazySeq seq "LazySeq.java" 51]
  [clojure.lang.RT seq "RT.java" 535]
  [clojure.core$seq__5467 invokeStatic "core.clj" 139]
  [clojure.core.protocols$seq_reduce invokeStatic "protocols.clj" 24]
  [clojure.core.protocols$fn__8236 invokeStatic "protocols.clj" 75]
  [clojure.core.protocols$fn__8236 invoke "protocols.clj" 75]
  [clojure.core.protocols$fn__8178$G__8173__8191 invoke "protocols.clj" 13]
  [clojure.core$reduce invokeStatic "core.clj" 6882]
  [clojure.core$reduce invoke "core.clj" 6868]
  [flatland.ordered.set.OrderedSet hashCode "set.clj" 59]
...
```

Comes from unconditionally calling `.hashCode` on all of the contained items:

https://github.com/clj-commons/ordered/blob/8cc133da590c2dd84e370899be03b26958a6a27f/src/flatland/ordered/set.clj#L59

I believe this could be solved by either using `clojure.core/hash` or by changing to a `keep` (which is fine because the hash of `nil` is 0):

```clojure
(reduce + (keep #(when % (.hashCode ^Object %)) (.seq this))))

**Comment by borkdude** [comment]
Sounds good to me

**Comment by jafingerhut** [comment]
Sorry if I am belaboring the obvious, but definitely good to add a test case that compares `.hashCode` of an ordered set against `.hashCode` of Clojure's built-in set type, both containing a `nil` element (and a few other chosen elements) to verify that they are the same with whatever code changes you make.

**Comment by NoahTheDuke** [comment]
Seems there was an incorrectly written test to check for this very thing. Oops!

**Comment by borkdude** [comment]
I don't think this issue is fixed since the hashcode for set with `nil` will be the same as hash-set with `false` now.

**Comment by NoahTheDuke** [comment]
Ah dang, right you are.
